name: fetch-gh-release-binary
description: |
  GitHub Action to download binaries from GitHub releases and make them
  available for use in later steps.
inputs:
  owner:
    description: "Owner of the repo with the release asset"
    required: false
  repo:
    description: "Repo with the release asset"
    required: false
  version:
    description: "Version of the release asset to fetch, if unset, use latest"
    required: false
  asset-pattern:
    description: "Pattern the asset name must match"
    required: false
  install-path:
    description: "Where to put the installed binary"
    required: false
  verbose:
    default: false
    description: "whether to enable verbose logging"
    required: false
  GITHUB_TOKEN:
    required: false
runs:
  using: "composite"
  steps:
  - run: |

      curl -LO https://github.com/charlieegan3/airtable-contacts/releases/download/0.7.0/airtable-contacts_0.7.0_Linux_x86_64.tar.gz
      tar -zxf airtable-contacts_0.7.0_Linux_x86_64.tar.gz
      md5sum ./airtable-contacts


      go run main.go \
        "-owner=${{ inputs.owner }}" \
        "-repo=${{ inputs.repo }}" \
        "-version=${{ inputs.version }}" \
        "-asset-pattern=${{ inputs.asset-pattern }}" \
        "-install-path=${{ inputs.install-path }}" \
        "-verbose=${{ inputs.verbose }}"

      md5sum /usr/local/bin/airtable-contacts
    shell: bash
branding:
  icon: arrow-down-circle
  color: orange
