name: fetch-gh-release-binary
description: |
  GitHub Action to download binaries from GitHub releases and make them
  available for use in later steps.
inputs:
  owner:
    description: "Owner of the repo with the release asset"
    required: false
  repo:
    description: "Repo with the release asset"
    required: false
  version:
    description: "Version of the release asset to fetch, if unset, use latest"
    required: false
  asset-pattern:
    description: "Pattern the asset name must match"
    required: false
  install-path:
    description: "Where to put the installed binary"
    required: false
  verbose:
    default: false
    description: "whether to enable verbose logging"
    required: false
  GITHUB_TOKEN:
    required: false
  token:
    required: false
    description: "GitHub token to use for authentication"
    default: ""

runs:
  using: "composite"
  steps:
  - run: |
      VERSION=0.4.0
      BINARY_NAME=fetch-gh-release-binary
      ASSET_NAME=${BINARY_NAME}_${VERSION}_Linux_amd64.tar.gz

      echo Fetching https://github.com/threecommaio/fetch-gh-release-binary/releases/download/$VERSION/$ASSET_NAME

      curl -LO https://github.com/threecommaio/fetch-gh-release-binary/releases/download/$VERSION/$ASSET_NAME
      tar -zxf $ASSET_NAME

      ./$BINARY_NAME \
        "-owner=${{ inputs.owner }}" \
        "-repo=${{ inputs.repo }}" \
        "-version=${{ inputs.version }}" \
        "-asset-pattern=${{ inputs.asset-pattern }}" \
        "-install-path=${{ inputs.install-path }}" \
        "-verbose=${{ inputs.verbose }}" \
        "-token=${{ inputs.token }}"

      rm $BINARY_NAME
    shell: bash
branding:
  icon: arrow-down-circle
  color: orange
